In [1]:
import pandas as pd
import plotly.express as px

In [2]:
df = pd.read_csv("../data/data_formatted.csv")

In [11]:
categ_var = df.select_dtypes(exclude='number').columns.tolist() + ['registration_year', 'registration_month', 'cylinders', 'seats', 'doors']
categ_var

['fuel_type',
 'body_type',
 'transmission',
 'emissions_label',
 'turbo',
 'registration_year',
 'registration_month',
 'cylinders',
 'seats',
 'doors']

In [12]:
df.head()

,fuel_type,mileage_km,body_type,transmission,power_hp,warranty_months,emissions_label,price,length_mm,width_mm,...,turbo,consumption_city_l_100km,consumption_highway_l_100km,consumption_mixed_l_100km,co2_g_km,tank_capacity_l,registration_month,registration_year,trunk_dim_1,trunk_dim_2
0,Petrol,3900.0,Sedan,Manual,179.0,12.0,C,29000.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2,2023,NaN,NaN
1,Petrol,4000.0,Sedan,Manual,180.0,24.0,C,30500.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6,2023,NaN,NaN
2,Electric,1.0,Sedan,Automatic,154.0,36.0,0 EMISSIONS,43800.0,3673.0,1682.0,...,Turbo,0.0,0.0,0.0,NaN,0.0,9,2023,185.0,550.0
3,Electric,7.0,Sedan,Automatic,154.0,36.0,0 EMISSIONS,38990.0,3673.0,1682.0,...,Turbo,0.0,0.0,0.0,NaN,0.0,10,2023,185.0,550.0
4,Electric,10.0,Sedan,Automatic,154.0,36.0,0 EMISSIONS,35990.0,3673.0,1682.0,...,Turbo,0.0,0.0,0.0,NaN,0.0,8,2023,185.0,550.0

In [19]:
data_corr = df.select_dtypes(include='number').corr()

In [22]:


fig = px.imshow(data_corr.loc[['mileage_km', 'length_mm'], ['mileage_km', 'length_mm']], text_auto=True, aspect="auto")
fig.show()

In [14]:
df.loc[1].tolist()

['Petrol',
 np.float64(4000.0),
 'Sedan',
 'Manual',
 np.float64(180.0),
 np.float64(24.0),
 'C',
 np.float64(30500.0),
 np.float64(nan),
 np.float64(nan),
 np.float64(nan),
 np.float64(nan),
 np.float64(nan),
 np.float64(nan),
 np.float64(nan),
 np.float64(nan),
 np.float64(nan),
 nan,
 np.float64(nan),
 np.float64(nan),
 np.float64(nan),
 np.float64(nan),
 np.float64(nan),
 np.int64(6),
 np.int64(2023),
 np.float64(nan),
 np.float64(nan)]

In [16]:
df = pd.read_csv("../data/data_outliers_free.csv")
df[['registration_year', 'transmission', 'power_hp', 'mileage_km']]

       registration_year transmission  power_hp  mileage_km
0                   2023       Manual     179.0      3900.0
1                   2023       Manual     180.0      4000.0
2                   2023    Automatic     154.0         1.0
3                   2023    Automatic     154.0         7.0
4                   2023    Automatic     154.0        10.0
...                  ...          ...       ...         ...
94123               2018    Automatic     250.0     35294.0
94124               2015    Automatic     254.0    113000.0
94125               2018    Automatic     310.0     85000.0
94126               2017    Automatic     310.0     57000.0
94127               2021    Automatic     120.0      2854.0

[94128 rows x 4 columns]

In [24]:
df_top4 = df[['registration_year', 'transmission', 'power_hp', 'mileage_km']].copy()
df_top4['car_age'] = df_top4['registration_year'].apply(lambda x: 2025 - x)
df_top4.drop(columns={'registration_year'}, inplace=True)
df_top4.max()

transmission      Manual
power_hp           366.0
mileage_km      222412.0
car_age               31
dtype: object

In [25]:
min_max = df_top4.agg(['min', 'max'])#.reset_index().rename(columns={'index': 'Stat'})

In [26]:
min_max

    transmission  power_hp  mileage_km  car_age
min    Automatic      60.0         0.0        1
max       Manual     366.0    222412.0       31

In [35]:
min_max.to_csv("../data/top4_min_max.csv", index=False)

In [33]:
min_max.loc["min", "car_age"]

KeyError: 'min'

In [29]:
min_max

    transmission  power_hp  mileage_km  car_age
min    Automatic      60.0         0.0        1
max       Manual     366.0    222412.0       31

In [36]:
min_max.loc[0, "car_age"]

np.int64(1)

In [34]:
min_max = pd.read_csv("../data/top4_min_max.csv")
min_max

   Unnamed: 0 transmission  power_hp  mileage_km  car_age
0           0    Automatic      60.0         0.0        1
1           1       Manual     366.0    222412.0       31